# Generated by Django 2.2.12 on 2020-05-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charges', models.IntegerField(blank=True, null=True, verbose_name='Charges In %')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_code', models.CharField(blank=True, max_length=30, null=True)),
                ('sender_name', models.CharField(blank=True, max_length=30, null=True, verbose_name="Sender's Name")),
                ('sender_id_number', models.CharField(blank=True, max_length=30, null=True, verbose_name="Sender's ID Number")),
                ('sender_address', models.CharField(blank=True, max_length=30, null=True, verbose_name="Sender's Address")),
                ('sender_phone_number', models.CharField(blank=True, max_length=30, null=True, verbose_name="Sender's Phone Number")),
                ('amount_sent', models.IntegerField(blank=True, null=True)),
                ('amount_receivable', models.IntegerField(blank=True, null=True)),
                ('recipient_name', models.CharField(blank=True, max_length=30, null=True, verbose_name="Recipient's Name")),
                ('recipient_id_number', models.CharField(blank=True, max_length=30, null=True, verbose_name="Recipient's ID Number")),
                ('recipient_address', models.CharField(blank=True, max_length=30, null=True, verbose_name="Recipient's Address")),
                ('recipient_phone_number', models.CharField(blank=True, max_length=30, null=True, verbose_name="Recipient's Phone Number")),
                ('time_sent', models.DateTimeField(auto_now_add=True)),
                ('tellerone', models.CharField(blank=True, max_length=30, null=True)),
                ('rate', models.IntegerField(blank=True, null=True, verbose_name='Current USD Rate')),
                ('charges', models.IntegerField(blank=True, null=True, verbose_name='Charges In %')),
                ('profit', models.IntegerField(blank=True, null=True, verbose_name='Company Total Earning')),
                ('received', models.BooleanField(default=False)),
                ('receive_by', models.CharField(blank=True, max_length=30, null=True, verbose_name='Received By')),
                ('time_received', models.DateTimeField(null=True)),
                ('tellertwo', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
