# Generated by Django 2.2.12 on 2020-05-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_transfer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='transfer_type',
            field=models.CharField(blank=True, choices=[('Local Transfer', 'Local Transfer'), ('US Transfer', 'US Transfer'), ('RIA', 'RIA'), ('Western Union', 'Western Union'), ('Money Gram', 'Money Gram'), ('TransFast', 'TransFast'), ('Small World', 'Small World')], default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='charges',
            name='charges',
            field=models.IntegerField(blank=True, null=True, verbose_name='Charges'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='charges',
            field=models.IntegerField(blank=True, null=True, verbose_name='Charges'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='profit',
            field=models.IntegerField(blank=True, null=True, verbose_name="Company's Total Earning"),
        ),
    ]
