# Generated by Django 2.2.12 on 2020-05-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200517_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='amount_sent',
            field=models.IntegerField(blank=True, null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transfer_code',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Pin Code'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transfer_type',
            field=models.CharField(blank=True, choices=[('Local Transfer', 'Local Transfer')], default='', max_length=50, null=True),
        ),
    ]
