# Generated by Django 2.2.12 on 2020-05-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200518_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transfer_type',
            field=models.CharField(blank=True, choices=[('Local Transfer', 'Local Transfer'), ('US Transfer', 'US Transfer'), ('RIA', 'RIA'), ('Western Union', 'Western Union'), ('Money Gram', 'Money Gram'), ('TransFast', 'TransFast'), ('Small World', 'Small World')], default='', max_length=50, null=True),
        ),
    ]
