# Generated by Django 2.2.12 on 2020-06-04 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200604_1032'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Branch_seven',
            new_name='Bakau_Branch_one',
        ),
        migrations.RenameModel(
            old_name='Branch_five',
            new_name='Bansan_two_Branch_nine',
        ),
        migrations.RenameModel(
            old_name='Branch_six',
            new_name='Basang_one_Branch_six',
        ),
        migrations.RenameModel(
            old_name='Branch_three',
            new_name='Basse_Branch_eleven',
        ),
        migrations.RenameModel(
            old_name='Branch_twelve',
            new_name='Brikamaba_Branch_eight',
        ),
        migrations.RenameModel(
            old_name='Branch_one',
            new_name='Brufut_Branch_three',
        ),
        migrations.RenameModel(
            old_name='Branch_eight',
            new_name='Brusubi_Branch_two',
        ),
        migrations.RenameModel(
            old_name='Branch_two',
            new_name='Jangjangbureh_Branch_seven',
        ),
        migrations.RenameModel(
            old_name='Branch_eleven',
            new_name='Sinchu_Branch_twelve',
        ),
        migrations.RenameModel(
            old_name='Branch_nine',
            new_name='Soma_Branch_ten',
        ),
        migrations.RenameModel(
            old_name='Branch_ten',
            new_name='Tallinding_Branch_four',
        ),
        migrations.RenameModel(
            old_name='Branch_four',
            new_name='Tipper_Garage_Branch_five',
        ),
    ]
