# Generated by Django 2.2.12 on 2020-06-07 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200604_2345'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bansan_two_Branch_nine',
            new_name='Bansang_two_branch_nine',
        ),
    ]
