# Generated by Django 2.2.12 on 2020-06-07 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200607_1242'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Basang_one_Branch_six',
            new_name='Bansang_one_branch_six',
        ),
    ]
