# Generated by Django 2.2.12 on 2020-06-07 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200607_1247'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tipper_Garage_Branch_five',
            new_name='Tipper_garrage_branch_five',
        ),
    ]
